development:
  sessions:
    default:
      database: forkbit_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  sessions:
    default:
      database: forkbit_test
      hosts:
        - localhost:27017
      options:
  options:

production:   
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true